### ISSUE TITLE
「Unable to find PostgreSQL client library.」の原因調査

### ISSUE THREAD

**Issue by harutoreon** [harutoreon/surface-treatment-manager#24]
## 概要
Rednerへのデプロイ中に発生した、PostgreSQLクライアントライブラリが見つからなかったエラーについての原因調査。

## 変更点
- https://github.com/harutoreon/surface-treatment-manager/pull/23

**Comment by harutoreon** [comment]
```
#13 19.85 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#13 19.85
#13 19.85     current directory: /usr/local/bundle/ruby/3.2.0/gems/pg-1.5.4/ext
#13 19.85 /usr/local/bin/ruby -I /usr/local/lib/ruby/3.2.0 extconf.rb
#13 19.85 Calling libpq with GVL unlocked
#13 19.85 checking for pg_config... no
#13 19.85 checking for libpq per pkg-config... no
#13 19.85 Using libpq from
#13 19.85 checking for libpq-fe.h... no
#13 19.85 Can't find the 'libpq-fe.h header
```

**Comment by harutoreon** [comment]
```
*****************************************************************************
#13 19.85
#13 19.85 Unable to find PostgreSQL client library.
#13 19.85
#13 19.85 Please install libpq or postgresql client package like so:
#13 19.85   sudo apt install libpq-dev
#13 19.85   sudo yum install postgresql-devel
#13 19.85   sudo zypper in postgresql-devel
#13 19.85   sudo pacman -S postgresql-libs
#13 19.85
#13 19.85 or try again with:
#13 19.85   gem install pg -- --with-pg-config=/path/to/pg_config
#13 19.85
#13 19.85 or set library paths manually with:
#13 19.85 gem install pg -- --with-pg-include=/path/to/libpq-fe.h/
#13 19.85 --with-pg-lib=/path/to/libpq.so/
```

**Comment by harutoreon** [comment]
```
#13 19.85 *** extconf.rb failed ***
#13 19.85 Could not create Makefile due to some reason, probably lack of necessary
#13 19.85 libraries and/or headers.  Check the mkmf.log file for more details.  You may
#13 19.85 need configuration options.
#13 19.85
#13 19.85 Provided configuration options:
#13 19.85   --with-opt-dir
#13 19.85   --without-opt-dir
#13 19.85   --with-opt-include
#13 19.85   --without-opt-include=${opt-dir}/include
#13 19.85   --with-opt-lib
#13 19.85   --without-opt-lib=${opt-dir}/lib
#13 19.85   --with-make-prog
#13 19.85   --without-make-prog
#13 19.85   --srcdir=.
#13 19.85   --curdir
#13 19.85   --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
#13 19.85   --with-pg
#13 19.85   --without-pg
#13 19.85   --enable-gvl-unlock
#13 19.85   --disable-gvl-unlock
#13 19.85   --enable-windows-cross
#13 19.85   --disable-windows-cross
#13 19.85   --with-pg-config
#13 19.85   --without-pg-config
#13 19.85   --with-pg_config
#13 19.85   --without-pg_config
#13 19.85   --with-libpq-dir
#13 19.85   --without-libpq-dir
#13 19.85   --with-libpq-include
#13 19.85   --without-libpq-include=${libpq-dir}/include
#13 19.85   --with-libpq-lib
#13 19.85   --without-libpq-lib=${libpq-dir}/lib
#13 19.85   --with-libpq-config
#13 19.85   --without-libpq-config
#13 19.85   --with-pkg-config
#13 19.85   --without-pkg-config
#13 19.85   --with-pg-dir
#13 19.85   --without-pg-dir
#13 19.85   --with-pg-include
#13 19.85   --without-pg-include=${pg-dir}/include
#13 19.85   --with-pg-lib
#13 19.85   --without-pg-lib=${pg-dir}/lib
```

**Comment by harutoreon** [comment]
```
#13 19.85 To see why this extension failed to compile, please check the mkmf.log which can
#13 19.85
#13 19.85 be found here:
#13 19.85   /usr/local/bundle/ruby/3.2.0/extensions/x86_64-linux/3.2.0/pg-1.5.4/mkmf.log
#13 19.85
#13 19.85 extconf failed, exit code 1
#13 19.85
#13 19.85 Gem files will remain installed in /usr/local/bundle/ruby/3.2.0/gems/pg-1.5.4
#13 19.85 for inspection.
#13 19.85 Results logged to
#13 19.85 /usr/local/bundle/ruby/3.2.0/extensions/x86_64-linux/3.2.0/pg-1.5.4/gem_make.out
#13 19.85
#13 19.85   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:102:in `run'
#13 19.85   /usr/local/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
#13 19.85   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:171:in `build_extension'
#13 19.85 /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:205:in `block in
#13 19.85 build_extensions'
#13 19.85   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:202:in `each'
#13 19.85   /usr/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:202:in `build_extensions'
#13 19.85   /usr/local/lib/ruby/3.2.0/rubygems/installer.rb:843:in `build_extensions'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/rubygems_gem_installer.rb:72:in
#13 19.85 `build_extensions'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/rubygems_gem_installer.rb:28:in
#13 19.85 `install'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:203:in
#13 19.85 `install'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/installer/gem_installer.rb:54:in
#13 19.85 `install'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/installer/gem_installer.rb:16:in
#13 19.85 `install_from_spec'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/installer/parallel_installer.rb:156:in
#13 19.85 `do_install'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/installer/parallel_installer.rb:147:in
#13 19.85 `block in worker_pool'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:62:in
#13 19.85 `apply_func'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:57:in
#13 19.85 `block in process_queue'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in
#13 19.85 `loop'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in
#13 19.85 `process_queue'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:90:in
#13 19.85 `block (2 levels) in create_threads'
#13 19.85
#13 19.85 An error occurred while installing pg (1.5.4), and Bundler cannot continue.
#13 19.85
#13 19.85 In Gemfile:
#13 19.85   pg
#13 ERROR: process "/bin/sh -c bundle install &&     rm -rf ~/.bundle/ \"${BUNDLE_PATH}\"/ruby/*/cache \"${BUNDLE_PATH}\"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile" did not complete successfully: exit code: 5
------
 > [build 3/6] RUN bundle install &&     rm -rf ~/.bundle/ "/usr/local/bundle"/ruby/*/cache "/usr/local/bundle"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile:
#13 19.85 `loop'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in
#13 19.85 `process_queue'
#13 19.85 /usr/local/bundle/ruby/3.2.0/gems/bundler-2.4.20/lib/bundler/worker.rb:90:in
#13 19.85 `block (2 levels) in create_threads'
#13 19.85
#13 19.85 An error occurred while installing pg (1.5.4), and Bundler cannot continue.
#13 19.85
#13 19.85 In Gemfile:
#13 19.85   pg
------
Dockerfile:26
--------------------
  25 |     COPY Gemfile Gemfile.lock ./
  26 | >>> RUN bundle install && \
  27 | >>>     rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
  28 | >>>     bundle exec bootsnap precompile --gemfile
  29 |
--------------------
error: failed to solve: process "/bin/sh -c bundle install &&     rm -rf ~/.bundle/ \"${BUNDLE_PATH}\"/ruby/*/cache \"${BUNDLE_PATH}\"/ruby/*/bundler/gems/*/.git &&     bundle exec bootsnap precompile --gemfile" did not complete successfully: exit code: 5
error: exit status 1
```

**Comment by harutoreon** [comment]
上記の情報から、$ sudo apt install libpq-dev を実行してlibpgライブラリをインストール。

**Comment by harutoreon** [comment]
ビルドとデプロイは成功したが、データベースがSQLiteだった。
このIssueは一旦クローズして別 Issueにて対応する。
